# Phase 0 of the taxon crosswalk plan
# (`.claude/plans/2026-09-02 Taxon crosswalk — …md`): a fixed-point snapshot of
# the PROMOTED release's taxon / dataset_taxon / taxon_group tables, dumped by
# `data-raw/build_taxon_parity_fixture.R` from `calcofi4r::cc_get_db()` (never
# regenerated by a test — this pins the fixture itself, not calcofi4db logic).
# Phase 1+ compares a rebuilt shard against this fixture for parity; this test
# only asserts the fixture is internally sound: the row counts match its own
# README and every declared primary key is unique.

FIX_DIR <- test_path("fixtures", "taxon_parity_v2026.08.25")

read_fixture <- function(name)
  utils::read.csv(file.path(FIX_DIR, name), colClasses = "character",
                   na.strings = "")

test_that("taxon_parity_v2026.08.25 fixture files exist", {
  skip_if_not(dir.exists(FIX_DIR), "parity fixture not present")
  expect_true(file.exists(file.path(FIX_DIR, "taxon.csv")))
  expect_true(file.exists(file.path(FIX_DIR, "dataset_taxon.csv")))
  expect_true(file.exists(file.path(FIX_DIR, "taxon_group.csv")))
  expect_true(file.exists(file.path(FIX_DIR, "common_name_changes.csv")))
  expect_true(file.exists(file.path(FIX_DIR, "README.md")))
})

test_that("taxon fixture: row count and taxon_key uniqueness", {
  skip_if_not(dir.exists(FIX_DIR), "parity fixture not present")
  taxon <- read_fixture("taxon.csv")
  expect_equal(nrow(taxon), 2125L)
  expect_equal(anyDuplicated(taxon$taxon_key), 0L)
  expect_false(anyNA(taxon$taxon_key))
})

test_that("dataset_taxon fixture: row count and ds_taxon_key uniqueness", {
  skip_if_not(dir.exists(FIX_DIR), "parity fixture not present")
  dataset_taxon <- read_fixture("dataset_taxon.csv")
  expect_equal(nrow(dataset_taxon), 1910L)
  expect_equal(anyDuplicated(dataset_taxon$ds_taxon_key), 0L)
  expect_false(anyNA(dataset_taxon$ds_taxon_key))
  # every dataset_taxon.taxon_key resolves to a taxon row (FK, not just shape)
  taxon <- read_fixture("taxon.csv")
  expect_true(all(dataset_taxon$taxon_key %in% taxon$taxon_key))
})

test_that("taxon_group fixture: row count and (taxon_group_key, taxon_key) uniqueness", {
  skip_if_not(dir.exists(FIX_DIR), "parity fixture not present")
  taxon_group <- read_fixture("taxon_group.csv")
  expect_equal(nrow(taxon_group), 151L)
  pk <- paste(taxon_group$taxon_group_key, taxon_group$taxon_key)
  expect_equal(anyDuplicated(pk), 0L)
  taxon <- read_fixture("taxon.csv")
  expect_true(all(taxon_group$taxon_key %in% taxon$taxon_key))
})

test_that("D5 common_name_changes fixture: one row per changed taxon_key, all real taxa", {
  skip_if_not(dir.exists(FIX_DIR), "parity fixture not present")
  chg <- read_fixture("common_name_changes.csv")
  taxon <- read_fixture("taxon.csv")
  expect_equal(anyDuplicated(chg$taxon_key), 0L)
  expect_true(all(chg$taxon_key %in% taxon$taxon_key))
  expect_true(all(chg$source_rank %in% "manual" |
                    chg$source_rank == "swfsc_ichthyo" |
                    chg$source_rank == "worms_single" |
                    grepl("^other:", chg$source_rank) |
                    chg$source_rank == "empty"))
  # measured count for the plan's Phase 0 "Measured" line (D5 vs. v2026.08.25)
  expect_equal(nrow(chg), 49L)
})
